var datatable = {
    "data": [{
        "Constituency": "Mahim",
            "Candidate": "Sada Sarvankar",
            "Party": "Shiv Sena",
            "Total_assets": "₹7.06 crore",
            "Moveable_assets": "₹3.97",
            "Immoveable_assets": "₹3.09",
            "Total_Cases": 27,
            "Murder_charges": 1,
            "Kidnapping_charges": 0,
            "Dacoity_charges": 0,
            "Crimes_women": 0
    }, {
        "Constituency": "Ghatkopar West",
            "Candidate": "Ram Kadam",
            "Party": "BJP",
            "Total_assets": "₹40.77 crore",
            "Moveable_assets": "₹27.11",
            "Immoveable_assets": "₹13.65",
            "Total_Cases": 12,
            "Murder_charges": 1,
            "Kidnapping_charges": 1,
            "Dacoity_charges": 0,
            "Crimes_women": 0
    }, {
        "Constituency": "Ghatkopar East",
            "Candidate": "Prakash Mehta",
            "Party": "BJP",
            "Total_assets": "₹32.03 crore",
            "Moveable_assets": "₹5.01",
            "Immoveable_assets": "₹27.03",
            "Total_Cases": 12,
            "Murder_charges": 0,
            "Kidnapping_charges": 0,
            "Dacoity_charges": 0,
            "Crimes_women": 0
    }, {
        "Constituency": "Mankhurd Shivaji Nagar",
            "Candidate": "Abu Azmi",
            "Party": "Samajwadi Party",
            "Total_assets": "₹156.11 crore",
            "Moveable_assets": "₹126.57",
            "Immoveable_assets": "₹28.54",
            "Total_Cases": 12,
            "Murder_charges": 0,
            "Kidnapping_charges": 0,
            "Dacoity_charges": 0,
            "Crimes_women": 0
    }, {
        "Constituency": "Mulund",
            "Candidate": "Sardar Tara Singh",
            "Party": "BJP",
            "Total_assets": "₹18.46 crore",
            "Moveable_assets": "₹5.90",
            "Immoveable_assets": "₹12.55",
            "Total_Cases": 9,
            "Murder_charges": 0,
            "Kidnapping_charges": 0,
            "Dacoity_charges": 0,
            "Crimes_women": 1
    }, {
        "Constituency": "Sewri",
            "Candidate": "Ajay Choudhari",
            "Party": "Shiv Sena",
            "Total_assets": "₹4.75 crore",
            "Moveable_assets": "₹0.80",
            "Immoveable_assets": "₹3.95",
            "Total_Cases": 9,
            "Murder_charges": 0,
            "Kidnapping_charges": 0,
            "Dacoity_charges": 0,
            "Crimes_women": 0
    }, {
        "Constituency": "Bhandup West",
            "Candidate": "Ashok Patil",
            "Party": "Shiv Sena",
            "Total_assets": "₹2.06 crore",
            "Moveable_assets": "₹0.41",
            "Immoveable_assets": "₹1.64",
            "Total_Cases": 7,
            "Murder_charges": 0,
            "Kidnapping_charges": 0,
            "Dacoity_charges": 0,
            "Crimes_women": 0
    }, {
        "Constituency": "Colaba",
            "Candidate": "Raj Purohit",
            "Party": "BJP",
            "Total_assets": "₹2.62 crore",
            "Moveable_assets": "₹2.16",
            "Immoveable_assets": "₹0.46",
            "Total_Cases": 7,
            "Murder_charges": 0,
            "Kidnapping_charges": 0,
            "Dacoity_charges": 0,
            "Crimes_women": 0
    }, {
        "Constituency": "Magathane",
            "Candidate": "Prakash Surve",
            "Party": "Shiv Sena",
            "Total_assets": "₹12.17 crore",
            "Moveable_assets": "₹1.06",
            "Immoveable_assets": "₹11.11",
            "Total_Cases": 5,
            "Murder_charges": 0,
            "Kidnapping_charges": 0,
            "Dacoity_charges": 0,
            "Crimes_women": 0
    }, {
        "Constituency": "Vikhroli",
            "Candidate": "Sunil Raut",
            "Party": "Shiv Sena",
            "Total_assets": "₹2.10 crore",
            "Moveable_assets": "₹0.25",
            "Immoveable_assets": "₹1.85",
            "Total_Cases": 5,
            "Murder_charges": 1,
            "Kidnapping_charges": 0,
            "Dacoity_charges": 0,
            "Crimes_women": 1
    }, {
        "Constituency": "Jogeshwari East",
            "Candidate": "Ravindra Waikar",
            "Party": "Shiv Sena",
            "Total_assets": "₹20.51 crore",
            "Moveable_assets": "₹9.94",
            "Immoveable_assets": "₹10.58",
            "Total_Cases": 4,
            "Murder_charges": 0,
            "Kidnapping_charges": 0,
            "Dacoity_charges": 0,
            "Crimes_women": 0
    }, {
        "Constituency": "Anushakti Nagar",
            "Candidate": "Tukaram Kate",
            "Party": "Shiv Sena",
            "Total_assets": "₹1.38 crore",
            "Moveable_assets": "₹0.13",
            "Immoveable_assets": "₹1.24",
            "Total_Cases": 3,
            "Murder_charges": 0,
            "Kidnapping_charges": 0,
            "Dacoity_charges": 0,
            "Crimes_women": 0
    }, {
        "Constituency": "Malad West",
            "Candidate": "Aslam Shaikh",
            "Party": "INC",
            "Total_assets": "₹3.69 crore",
            "Moveable_assets": "₹1.66",
            "Immoveable_assets": "₹2.03",
            "Total_Cases": 2,
            "Murder_charges": 0,
            "Kidnapping_charges": 0,
            "Dacoity_charges": 0,
            "Crimes_women": 0
    }, {
        "Constituency": "Andheri East",
            "Candidate": "Ramesh Latke",
            "Party": "Shiv Sena",
            "Total_assets": "₹3.48 crore",
            "Moveable_assets": "₹1.30",
            "Immoveable_assets": "₹2.18",
            "Total_Cases": 2,
            "Murder_charges": 0,
            "Kidnapping_charges": 0,
            "Dacoity_charges": 0,
            "Crimes_women": 0
    }, {
        "Constituency": "Kurla",
            "Candidate": "Mangesh Kudalkar",
            "Party": "Shiv Sena",
            "Total_assets": "₹1.02 crore",
            "Moveable_assets": "₹0.07",
            "Immoveable_assets": "₹0.95",
            "Total_Cases": 2,
            "Murder_charges": 1,
            "Kidnapping_charges": 0,
            "Dacoity_charges": 0,
            "Crimes_women": 0
    }, {
        "Constituency": "Bandra West",
            "Candidate": "Ashish Shelar",
            "Party": "BJP",
            "Total_assets": "₹5.01 crore",
            "Moveable_assets": "₹1.44",
            "Immoveable_assets": "₹3.57",
            "Total_Cases": 2,
            "Murder_charges": 0,
            "Kidnapping_charges": 0,
            "Dacoity_charges": 0,
            "Crimes_women": 0
    }, {
        "Constituency": "Worli",
            "Candidate": "Sunil Shinde",
            "Party": "Shiv Sena",
            "Total_assets": "₹4.34 crore",
            "Moveable_assets": "₹1.56",
            "Immoveable_assets": "₹2.78",
            "Total_Cases": 2,
            "Murder_charges": 0,
            "Kidnapping_charges": 0,
            "Dacoity_charges": 0,
            "Crimes_women": 0
    }, {
        "Constituency": "Borivli",
            "Candidate": "Vinod Tawde",
            "Party": "BJP",
            "Total_assets": "₹6.98 crore",
            "Moveable_assets": "₹2.63",
            "Immoveable_assets": "₹4.35",
            "Total_Cases": 1,
            "Murder_charges": 0,
            "Kidnapping_charges": 0,
            "Dacoity_charges": 0,
            "Crimes_women": 0
    }, {
        "Constituency": "Dahisar",
            "Candidate": "Manisha Chaudhury",
            "Party": "BJP",
            "Total_assets": "₹7.52 crore",
            "Moveable_assets": "₹1.83",
            "Immoveable_assets": "₹5.69",
            "Total_Cases": 1,
            "Murder_charges": 0,
            "Kidnapping_charges": 0,
            "Dacoity_charges": 0,
            "Crimes_women": 0
    }, {
        "Constituency": "Kandivli East",
            "Candidate": "Atul Bhatkalkar",
            "Party": "BJP",
            "Total_assets": "₹2.68 crore",
            "Moveable_assets": "₹1.43",
            "Immoveable_assets": "₹1.25",
            "Total_Cases": 1,
            "Murder_charges": 0,
            "Kidnapping_charges": 0,
            "Dacoity_charges": 0,
            "Crimes_women": 0
    }, {
        "Constituency": "Vile Parle",
            "Candidate": "Parag Alavani",
            "Party": "BJP",
            "Total_assets": "₹24.25 crore",
            "Moveable_assets": "₹1.19",
            "Immoveable_assets": "₹23.05",
            "Total_Cases": 1,
            "Murder_charges": 0,
            "Kidnapping_charges": 0,
            "Dacoity_charges": 0,
            "Crimes_women": 0
    }, {
        "Constituency": "Kalina",
            "Candidate": "Sanjay Potnis",
            "Party": "Shiv Sena",
            "Total_assets": "₹2.33 crore",
            "Moveable_assets": "₹0.58",
            "Immoveable_assets": "₹1.76",
            "Total_Cases": 1,
            "Murder_charges": 0,
            "Kidnapping_charges": 0,
            "Dacoity_charges": 0,
            "Crimes_women": 0
    }, {
        "Constituency": "Dindoshi",
            "Candidate": "Sunil Prabhu",
            "Party": "Shiv Sena",
            "Total_assets": "₹4.04 crore",
            "Moveable_assets": "₹0.54",
            "Immoveable_assets": "₹3.50",
            "Total_Cases": 0,
            "Murder_charges": 0,
            "Kidnapping_charges": 0,
            "Dacoity_charges": 0,
            "Crimes_women": 0
    }, {
        "Constituency": "Charkop",
            "Candidate": "Yogesh Sagar",
            "Party": "BJP",
            "Total_assets": "₹1.91 crore",
            "Moveable_assets": "₹1.10",
            "Immoveable_assets": "₹0.81",
            "Total_Cases": 0,
            "Murder_charges": 0,
            "Kidnapping_charges": 0,
            "Dacoity_charges": 0,
            "Crimes_women": 0
    }, {
        "Constituency": "Goregaon",
            "Candidate": "Vidya Thakur",
            "Party": "BJP",
            "Total_assets": "₹10.25 crore",
            "Moveable_assets": "₹3.00",
            "Immoveable_assets": "₹7.24",
            "Total_Cases": 0,
            "Murder_charges": 0,
            "Kidnapping_charges": 0,
            "Dacoity_charges": 0,
            "Crimes_women": 0
    }, {
        "Constituency": "Versova",
            "Candidate": "Bharati Lavekar",
            "Party": "BJP",
            "Total_assets": "₹1.57 crore",
            "Moveable_assets": "₹0.75",
            "Immoveable_assets": "₹0.82",
            "Total_Cases": 0,
            "Murder_charges": 0,
            "Kidnapping_charges": 0,
            "Dacoity_charges": 0,
            "Crimes_women": 0
    }, {
        "Constituency": "Andheri West",
            "Candidate": "Ameet Satam",
            "Party": "BJP",
            "Total_assets": "₹2.03 crore",
            "Moveable_assets": "₹0.93",
            "Immoveable_assets": "₹1.10",
            "Total_Cases": 0,
            "Murder_charges": 0,
            "Kidnapping_charges": 0,
            "Dacoity_charges": 0,
            "Crimes_women": 0
    }, {
        "Constituency": "Chandivli",
            "Candidate": "Naseem Khan",
            "Party": "INC",
            "Total_assets": "₹9.07 crore",
            "Moveable_assets": "₹4.96",
            "Immoveable_assets": "₹4.11",
            "Total_Cases": 0,
            "Murder_charges": 0,
            "Kidnapping_charges": 0,
            "Dacoity_charges": 0,
            "Crimes_women": 0
    }, {
        "Constituency": "Chembur",
            "Candidate": "Prakash Phaterpekar",
            "Party": "Shiv Sena",
            "Total_assets": "₹2.74 crore",
            "Moveable_assets": "₹1.19",
            "Immoveable_assets": "₹1.55",
            "Total_Cases": 0,
            "Murder_charges": 0,
            "Kidnapping_charges": 0,
            "Dacoity_charges": 0,
            "Crimes_women": 0
    }, {
        "Constituency": "Bandra East",
            "Candidate": "Prakash (Bala) Sawant",
            "Party": "Shiv Sena",
            "Total_assets": "₹2.25 crore",
            "Moveable_assets": "₹0.85",
            "Immoveable_assets": "₹1.40",
            "Total_Cases": 0,
            "Murder_charges": 0,
            "Kidnapping_charges": 0,
            "Dacoity_charges": 0,
            "Crimes_women": 0
    }, {
        "Constituency": "Dharavi",
            "Candidate": "Varsha Gaikwad",
            "Party": "INC",
            "Total_assets": "₹2.24 crore",
            "Moveable_assets": "₹0.38",
            "Immoveable_assets": "₹1.86",
            "Total_Cases": 0,
            "Murder_charges": 0,
            "Kidnapping_charges": 0,
            "Dacoity_charges": 0,
            "Crimes_women": 0
    }, {
        "Constituency": "Sion Koliwada",
            "Candidate": "R. Tamil Selvan",
            "Party": "BJP",
            "Total_assets": "₹2.44 crore",
            "Moveable_assets": "₹0.87",
            "Immoveable_assets": "₹1.57",
            "Total_Cases": 0,
            "Murder_charges": 0,
            "Kidnapping_charges": 0,
            "Dacoity_charges": 0,
            "Crimes_women": 0
    }, {
        "Constituency": "Wadala",
            "Candidate": "Kalidas Kolambkar",
            "Party": "Shiv Sena",
            "Total_assets": "₹7.79 crore",
            "Moveable_assets": "₹1.35",
            "Immoveable_assets": "₹6.44",
            "Total_Cases": 0,
            "Murder_charges": 0,
            "Kidnapping_charges": 0,
            "Dacoity_charges": 0,
            "Crimes_women": 0
    }, {
        "Constituency": "Byculla",
            "Candidate": "Waris Yusuf Pathan",
            "Party": "MIM",
            "Total_assets": "₹3.06 crore",
            "Moveable_assets": "₹0.19",
            "Immoveable_assets": "₹2.87",
            "Total_Cases": 0,
            "Murder_charges": 0,
            "Kidnapping_charges": 0,
            "Dacoity_charges": 0,
            "Crimes_women": 0
    }, {
        "Constituency": "Malabar Hill",
            "Candidate": "Mangal Prabhat Lodha",
            "Party": "BJP",
            "Total_assets": "₹198.62 crore",
            "Moveable_assets": "₹61.54",
            "Immoveable_assets": "₹137.08",
            "Total_Cases": 0,
            "Murder_charges": 0,
            "Kidnapping_charges": 0,
            "Dacoity_charges": 0,
            "Crimes_women": 0
    }, {
        "Constituency": "Mumbadevi",
            "Candidate": "Amin Patel",
            "Party": "INC",
            "Total_assets": "₹37.22 crore",
            "Moveable_assets": "₹22.71",
            "Immoveable_assets": "₹14.51",
            "Total_Cases": 0,
            "Murder_charges": 0,
            "Kidnapping_charges": 0,
            "Dacoity_charges": 0,
            "Crimes_women": 0
    }]
};